### ISSUE TITLE
Stronger queries

### ISSUE THREAD

**Issue by dustinlacewell** [grebaldi/nopun-ecs#9]
I'm currently reviewing TypeScript ECS libraries and I have to say you're doing a great job.

However, one feature that that nopun is lacking in is the power of its queries. While it does have the very nice feature of being able to specify multiple queries per system (which is very cool, and unique), the queries are limited to a list of AND'd components.

Do you have any plan on extending the current query system so you can do some of the typical `oneOf`, `allOf`, `noneOf`, etc?

**Comment by grebaldi** [comment]
Thanks a lot for your feedback, @dustinlacewell!

So far I didn't have the need for more complex queries. Thinking about it right now,  it shouldn't be too hard add them. 

In fact, as I was writing the statement above, I started scribbling around a little and came up with a PR (see: https://github.com/grebaldi/nopun-ecs/pull/10) that adds some more query operations. I went for a boolean naming convention, so the operations are:

- `And(Component1, Component2, ...)`
- `Or(Component1, Component2, ...)`
- `Not(Component1, Component2, ...)`
- `Xor(Component1, Component2, ...)`

All operations can be combined, e.g.:

```js
Or(Xor(Component1, And(Component2, Component3)), Not(Component4))
```

The PR can be tested in a project with:

```
yarn add github:grebaldi/nopun-ecs#pull/10/head
cd node_modules/nopun-ecs && yarn && make build; cd -
```
It would be great to get your feedback on whether this works for you. If so, I'll finish this up and release v1.3.0 :)
